apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: kube
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30080
  type: NodePort
